-- Script amélioré pour ajouter 117 animations SnapEvent
-- Source: animations_snapevent_propre.xlsx
-- Types d'animations correctement mappés

-- Vérification avant insertion
SELECT COUNT(*) as animations_avant_ajout FROM animations;

-- Insertion des animations SnapEvent avec types corrects
INSERT INTO animations (nom, type_animation, description, capacite, duree, prix, contact, url) VALUES
('Animation photo - Box Néon', 'Animation Photo Vidéo', 'Découvrez la magie de notre animation Box Néon : une expérience lumineuse inédite. Prêt à plonger dans l''univers étincelant de notre Box Néon ? Let''s glow !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/animation-photo-box-neon-1094'),
('Animation photo - Télésiège', 'Animation Photo Vidéo', 'Plongez dans une ambiance hivernale inédite grâce à notre animation télésiège ! Vous souhaitez ajouter une touche alpine à votre Winter Party ? Offrez un décor insolite à vos invités et immergez-les dans un univers montagnard. Notre télésiège créera des souvenirs chaleureux au cœur de l''hiver.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/animation-photo-telesiege-1093'),
('Cabine Studio photo Harcourt', 'Animation Photo Vidéo', 'Vivez la véritable expérience Harcourt avec notre cabine photo haut de gamme, pour des portraits emblématiques avec un éclairage studio et une esthétique élégante.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/cabine-studio-photo-harcourt-1092'),
('Cabine Photo ou Vidéo', 'Animation Photo Vidéo', 'Offrez un espace photo intime à vos invités ! La cabine photo est le secret pour des souvenirs mémorables. Laissez vos invités se glisser derrière le rideau et faire leur plus beau sourire en toute intimité ! Notre cabine photo se transforme aussi en cabine vidéo, avec un mode interview qui ajoute une touche de fun et d''authenticité à vos souvenirs.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/cabine-photo-ou-video-1091'),
('Borne Photo - Wonder Booth IA', 'Animation Photo Vidéo', 'Incarnez le personnage de votre choix avec la Wonder Booth IA. Parcourez notre catalogue de thèmes et choisissez celui qui vous inspire le plus parmi notre vaste choix de filtres. Une fois la photo prise, notre IA entre en action pour générer une image unique. Autres informations : - Sélection jusqu''à 20 filtres parmi un catalogue de propositions disponibles - La génération de Photo n''est pas identique. Tout le monde repartira avec un cliché unique - Une seule personne est prise en charge par...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/borne-photo-wonder-booth-ia-1090'),
('Selfie 360', 'Animation Photo Vidéo', 'L''animation vidéo selfie 360° est un photocall original pour vos événements. Ce vidéobooth 360 est l''animation video tiktok parfaite pour vos festivals et lancement de produits. Personnalisez votre vidéo avec l’univers de votre marque (bandeau, logo seul, bandeau dynamique...) Partagez instantanément votre vidéo via votre mail, sur les réseaux sociaux et mesurez l''impact !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/selfie-360-1010'),
('Reportage photo live', 'Animation Photo Vidéo', 'Ce concept réinvente la photo évènementielle à l''aide de la reconnaissance faciale et se présente comme une alternative à la borne photo 100% française, eco-responsable et sans papier. À l''aide d''un simple QR Code & d''un selfie, les invités reçoivent leurs photos en live, sans rien installer, de façon individualisée & privée. L''organisateur peut lui recevoir en live un accès à toutes les photos. Avec ou sans photocall, Bluffez vos invités en leur offrant un shooting photo de qualité professio...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/reportage-photo-live-1009'),
('Photobooth - Fresque collaborative', 'Animation Photo Vidéo', 'Créez votre Fresque Collaborative et découvrez l''art de la créativité partagée ! Comment ça fonctionne ? 1. Prenez une photo avec notre Wonder Booth 2. Choisissez un numéro 3. Collez votre cliché au bon endroit sur la fresque 4. Ensemble, dévoilez petit à petit votre visuel au travers des sourires de vos collaborateurs ou invités.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/photobooth-fresque-collaborative-842'),
('Animation photo - Balançoire', 'Animation Photo Vidéo', 'Apportez une touche plus fun et plus glamour à vos événements grâce à notre balançoire ! Installez-vous dessus et laissez-vous prendre en photo par la Wonder Booth pour immortaliser chaque instant de votre événement avec vos invités. Choisissez entre la balançoire bois ou acier et complétez la scénographie avec un fond fleuri ou végétal.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/animation-photo-balancoire-841'),
('Photobooth - Argentique', 'Animation Photo Vidéo', 'Découvrez cette technique de photo ancienne ambulante pour immortaliser les souvenirs clés de votre événement avec un tirage original. Nos photographes réalisent des photos en noir et blanc, en direct et sans artifices devant vous. Une fois le studio ambulant installé, la prise de vue et le développement des tirages se feront sous vos yeux, afin de vous faire participer au maximum à cette expérience photographique hors du temps. Durée : 4 h', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/photobooth-argentique-806'),
('Photobooth - Photomaton vintage', 'Animation Photo Vidéo', 'Louez une mini borne photo vintage pour vos évènements pour disposer de vos beaux souvenirs à porter de mains ! Avec sa petite taille, cette borne s''installe très facilement et dispose d''un débit de photo très rapide, 2 à 3 tirages/minute ! Installez-vous, prenez votre photo et repartez avec votre photo vintage.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/photobooth-photomaton-vintage-752'),
('Photobooth - Cabine vintage', 'Animation Photo Vidéo', 'Louez une cabine photo type photomaton pour tous vos évènements. Cet objet participe pleinement à rendre votre événement chaleureux ! C’est une animation fun qui permet à vos invités et à vos clients de repartir avec un souvenir vintage de leur passage ou même de les partager directement en ligne avec leurs amis ou leurs collègues. Aucune attente devant cette cabine puisque le débit de photo très rapide de 2 à 3 tirages/minute !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/photobooth-cabine-vintage-751'),
('Animation photo - Piscine à balles', 'Animation Photo Vidéo', 'Il n''y a pas que les enfants qui ont le droit de s''amuser ! Une baignade dans notre piscine à balles ça vous dit ? Offrez à vos invités une expérience fun et inoubliable grâce à notre piscine à balles pour décorer votre espace photo et immortalisez ce moment amusant.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/animation-photo-piscine-a-balles-667'),
('Borne Photo - Wonderbooth', 'Animation Photo Vidéo', 'Immortalisez votre événement avec style et capturez les sourires de vos invités. Placez la Wonder Booth à l''emplacement dédié aux photos et laissez la magie opérer ! Pour une expérience encore plus immersive, personnalisez les contours de la Wonder Booth et/ou ajoutez un fond personnalisé.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/borne-photo-wonderbooth-150'),
('Photographe pro', 'Animation Photo Vidéo', 'Il prend le temps de cerner la complexité des différents lieux et objets, pour un résultat à la hauteur de vos exigences. Photographe professionnel équipé de matériel pro se propose d''immortaliser vos événements. Une prestation de 2 heures (par exemple lors d''un cocktail, d''un dîner, d''une soirée, etc) avec à l''issue une centaine de photos retouchées de manière professionnelle.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/photo-video/photographe-pro-94'),
('Sega Racing Classic Daytona', 'Animation Jeux', 'L’esprit Daytona à pleine vitesse ! Revivez la magie des salles d’arcade avec Sega Racing Classic, la version modernisée du mythique Daytona USA ! Montez à bord de voitures de course survitaminées et affrontez vos adversaires sur des circuits emblématiques dans une ambiance survoltée. Doté des dernières technologies en matière de simulation, ce jeu vous offre un réalisme saisissant, aussi bien au niveau de la conduite que des sensations ressenties. L’ambiance sonore, les graphismes retravaill...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/sega-racing-classic-daytona-1184'),
('Simulateur Moto GP', 'Animation Jeux', 'Prenez la piste comme un vrai pilote ! Faites rugir les moteurs et ressentez la montée d’adrénaline avec MotoGP, le simulateur officiel qui vous propulse sur les circuits mythiques de la compétition moto la plus prestigieuse au monde ! Installez-vous sur une réplique authentique de moto de Grand Prix, penchez dans les virages comme les pros, et défiez les légendes de la discipline dans des courses endiablées. Grâce à un écran HD immersif, une caméra frontale, et un ventilateur intégré qui sou...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-moto-gp-1183'),
('Simulateur SnoCross Motoneige', 'Animation Jeux', 'La course givrée en motoneige ! Envie d’offrir une animation givrée qui décoiffe ? SnoCross de Raw Thrills vous embarque au cœur des sommets enneigés pour des courses de motoneige spectaculaires, en solo ou à deux, sur des pistes extrêmes où tous les coups sont permis ! Grâce à son écran HD de 42 pouces, ses commandes réalistes et son siège dynamique, vous êtes plongé dans une expérience immersive où la vitesse et le fun prennent le dessus. Pilotez, sautez, dérapez et laissez la poudreuse vol...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-snocross-motoneige-1182'),
('Simulateur Super Alpine Racer', 'Animation Jeux', 'La montagne vous attend à toute vitesse ! Préparez-vous à une descente à couper le souffle avec Super Alpine Racer, le simulateur de ski alpin ultime qui mêle vitesse, adrénaline et sensations fortes ! Idéal pour dynamiser vos événements avec une animation spectaculaire, ce jeu vous place sur les pistes les plus vertigineuses pour un défi sportif et immersif. Équipé d’un écran HD 55” et d’un souffleur d’air intégré pour simuler la vitesse, Super Alpine Racer vous fait littéralement sentir le ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-super-alpine-racer-1181'),
('Simulateur Snowboarder Raw Thrills', 'Animation Jeux', 'Dévalez les pistes comme un pro ! Envie d’une animation rafraîchissante et pleine de sensations ? Montez sur la planche avec Snowboarder de Raw Thrills, le simulateur de glisse qui vous plonge en plein cœur des montagnes enneigées pour une descente inoubliable ! Que vous soyez amateur de vitesse ou de technicité, deux modes de jeu s’offrent à vous : descente libre à fond les ballons ou slalom de précision. Grâce à sa plateforme interactive et ses commandes physiques ultra réactives, vous ress...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-snowboarder-raw-thrills-1180'),
('Simulateur de tir - Wild West Shootout', 'Animation Jeux', 'Plongez dans l’ambiance du Far West ! Transformez vos événements en véritable saloon grâce à Wild West Shootout, le jeu de tir d’arcade convivial, immersif et ultra ludique, accessible à tous les âges ! Idéal pour créer une animation originale, ce jeu transporte petits et grands dans l’univers palpitant du Far West, entre duels épiques, cibles à abattre et ambiance western garantie. Doté d’un écran HD pour une qualité graphique exceptionnelle, Wild West Shootout offre une prise en main immédi...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-tir-wild-west-shootout-1179'),
('Simulateur Jet Blaster', 'Animation Jeux', 'Sensations fortes garanties sur les vagues ! Envie de faire monter l’adrénaline avec une animation aussi dynamique que spectaculaire ? Jet Blaster est le simulateur de course aquatique nouvelle génération qui vous propulse au cœur de l’action, entre vagues déchaînées, sauts acrobatiques et vitesse pure ! Installé sur une plateforme de mouvement à cylindres, ce simulateur offre des sensations ultra réalistes : inclinaisons, secousses, effets de vent et vibrations vous plongent littéralement da...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-jet-blaster-1178'),
('Simulateur Sky Riders', 'Animation Jeux', 'Envolez-vous pour une aventure immersive, fun et sportive ! Faites décoller l’adrénaline avec Sky Riders, un simulateur de vol actif et innovant qui plonge les joueurs dans un univers 3D ultra réaliste ! Parfait pour dynamiser vos événements avec une animation aussi spectaculaire qu’interactive, ce jeu invite les participants à pédaler pour s’envoler, collecter des récompenses et franchir des obstacles aériens. Doté de deux écrans HD aux graphismes riches et détaillés, d’un souffleur d’air in...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-sky-riders-1177'),
('Simulateur conduite enfant (2 joueurs) - Big Foot Crush', 'Animation Jeux', 'Le simulateur de Monster Truck qui fait vibrer petits et grands ! Envie d’une animation familiale, fun et pleine de sensations pour vos événements ? Bigfoot Crush est le simulateur de conduite 2 joueurs sous licence officielle BIGFOOT®, le plus célèbre des monster trucks ! Une expérience immersive qui plaira autant aux enfants qu’aux parents amateurs de conduite tout-terrain. Installez-vous dans le cockpit et vivez le frisson de piloter un véritable camion monstre : accélérations, sauts, casc...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/simulateur-conduite-enfant-2-joueurs-big-foot-crush-1176'),
('Table Pong Atari / Table vidéo cocktail', 'Animation Jeux', 'Table Pong Atari Le rétro gaming réinventé en mobilier chic et convivial ! Apportez une touche d’originalité et de nostalgie à vos événements avec la table Pong sous licence officielle Atari ! Véritable hommage au tout premier jeu vidéo d’arcade des années 70, cette réplique modernisée est bien plus qu’un clin d’œil rétro : c’est une véritable œuvre design, aussi ludique qu’élégante. Dotée d’un mécanisme magnétique de haute précision, la balle et les raquettes se déplacent à vue sur la surfac...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/table-pong-atari-table-video-cocktail-1175'),
('Grue à pince', 'Animation Jeux', 'L’attraction ludique et personnalisable qui fait toujours sensation ! Offrez une animation originale, fun et irrésistible avec nos grues à pince, parfaites pour captiver petits et grands lors de tous vos événements ! Véritable incontournable des fêtes foraines et des arcades, cette machine iconique s’adapte à toutes les ambiances et apporte une touche vintage pleine de charme. Entièrement personnalisable (habillage, contenu, configuration), la grue à pince peut être fournie avec ou sans goodi...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/grue-a-pince-1174'),
('Machine à jeton - type slot Casino', 'Animation Jeux', 'L''ambiance Casino au cœur de votre événement ! Envie d’ajouter une touche glamour et ludique à votre événement ? Misez sur le fun avec nos machines à jetons type slot casino ! Inspirées des incontournables bandits manchots, elles recréent l’ambiance des plus grands casinos… sans jamais quitter votre lieu d’animation ! Le principe est simple et terriblement addictif : insérez vos jetons, puis appuyez successivement sur les trois boutons pour arrêter les rouleaux un par un. Suspense garanti à c...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/machine-a-jeton-type-slot-casino-1173'),
('Jeu de marteau pour enfants', 'Animation Jeux', 'Le classique des tout-petits pour des éclats de rire assurés ! Offrez aux plus jeunes une animation ludique, colorée et accessible dès le plus jeune âge avec notre Jeu de Marteau Enfant ! Inspiré des célèbres jeux de fête foraine, ce jeu invite les enfants dès 3 ans à attraper leur petit marteau et frapper sur les têtes qui apparaissent… le tout en rythme et avec le sourire ! Grâce à plusieurs niveaux de difficulté, les enfants peuvent progresser tout en s’amusant, développant ainsi coordinat...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/jeu-marteau-pour-enfants-1172'),
('Catch the light', 'Animation Jeux', 'Vitesse, réflexes et fun garantis ! Envie d’un défi explosif pour dynamiser votre événement ? Avec Catch the Light, testez vos réflexes et votre coordination dans un jeu frénétique et ultra compétitif ! Face à face, les joueurs s''affrontent pour taper le plus vite possible sur les boutons lumineux, tout en évitant les pièges… car toucher un bouton éteint vous fera perdre des points ! Simple à comprendre, ultra dynamique et terriblement addictif, Catch the Light crée immédiatement une ambiance...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/catch-the-light-1171'),
('Subsoccer', 'Animation Jeux', 'Le baby-foot humain qui fait fureur ! Préparez-vous à surprendre vos invités avec une animation originale, sportive et totalement fun : le Subsoccer 7, un baby-foot humain qui transforme une simple partie de foot en un duel intense et hilarant ! Le principe ? Deux joueurs s’installent face à face, chacun assis derrière sa cage, et s’affrontent dans une partie de 1 contre 1 où réflexes, précision et stratégie sont de mise. Le tout assis, mais pas moins compétitif ! L’objectif est simple : marq...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/subsoccer-1170'),
('Danse Machine', 'Animation Jeux', 'L’animation rythmée qui fait bouger tout le monde ! Envie de mettre l’ambiance et de faire bouger vos invités ? La Danse Machine est l’animation parfaite pour combiner musique, énergie et fun, dans un format interactif et ultra dynamique ! Le principe est simple : le joueur se place sur une plateforme équipée de flèches directionnelles, puis suit le rythme de la musique en appuyant avec ses pieds sur les flèches correspondantes qui défilent à l’écran. Coordination, rapidité et sens du tempo s...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/danse-machine-1169'),
('JukeBox', 'Animation Jeux', 'Jukebox Classique – L’authenticité à l’état pur Apportez une touche rétro inimitable à votre événement avec notre Jukebox Classique : un bijou de nostalgie au design iconique, parfait pour créer une ambiance chaleureuse et musicale en un clin d’œil. Avec une capacité de 48 CD, soit plus de 1000 titres disponibles, ce jukebox est équipé d’un lecteur Philips fiable, d’un amplificateur 200 watts et de 6 haut-parleurs, pour une qualité sonore puissante et enveloppante. Branchement sur alimentatio...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/jukebox-1168'),
('Street Basket', 'Animation Jeux', 'Un défi sportif et fun avec le Street Basket Arcade ! Ajoutez du rythme et de la compétition à vos événements avec le simulateur de Street Basket Arcade Sonic, une animation sportive, dynamique et accessible à tous ! Inspiré des terrains urbains, ce jeu d’arcade invite les participants à enchaîner un maximum de paniers en un temps limité, seul ou en duo. Simple à prendre en main mais ultra addictif, le Street Basket stimule réflexes, précision et esprit d’équipe. À mesure que les niveaux s’en...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/street-basket-1167'),
('Jeux forains : Boxeur - Mailloche - Kicker', 'Animation Jeux', 'Ambiance fête foraine garantie avec notre Pack Jeux Forains ! Envie d’ajouter du fun, du défi et un brin de nostalgie à votre événement ? Optez pour notre Pack Jeux Forains, un trio explosif d’animations interactives et ultra populaires, parfait pour réveiller l’esprit de compétition dans une ambiance décontractée et festive ! Le Boxeur Star des bars et fêtes foraines, cette machine iconique mesure la puissance du coup de poing. Un seul objectif : frapper fort dans la balle pour afficher le m...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/jeux-forains-boxeur-mailloche-kicker-1166'),
('Table de Ping-Pong', 'Animation Jeux', 'L’incontournable du jeu en plein air, version haut de gamme ! Apportez du dynamisme et une bonne dose de fun à vos événements avec notre table de ping-pong Cornilleau Outdoor, un modèle premium pensé pour la performance et la durabilité. Que ce soit pour un tournoi improvisé ou une partie détendue entre collègues, cette table offre une expérience de jeu fluide et professionnelle, en intérieur comme en extérieur. Dotée d’un panneau en aggloméré de 22 mm, d’un encadrement en acier anti-rayure e...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animations-ludiques/table-ping-pong-1165'),
('Artiste solo & saxophone', 'Animation Show', 'Un saxophone solo sur une bande son pour vos soirées élégantes, au choix : ✨Marin Galan pour du jazz ou pour accompagner un DJ ✨Mat Charvey pour du saxo à l''état pur ✨Mikosax pour son adaptabilité à tous les styles * La disponibilité des artistes est à confirmer auprès de nos chefs de projet.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/artiste-solo-saxophone-1101'),
('Artiste solo & guitare', 'Animation Show', 'De la chanson française à la pop internationales, ces artistes accompagnés de leur guitare vous feront voyager ! ✨Moē Walden pour un set tout en douceur et romantisme ✨Jakke pour chanter les incontournables tout en chœur ✨Sumana pour un voyage intime et solaire ✨Leen Ade pour de la folk 60-70s ou plus contemporaine * La disponibilité des artistes est à confirmer auprès de nos chefs de projet.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/artiste-solo-guitare-1100'),
('Karaoke', 'Animation Show', 'Transformez vos collaborateurs en véritables Rock Stars avec un Karaoké animé ! Un karaoké dirigé par un animateur professionnel L’idée est simple : faire chanter vos collaborateurs sur scène avec l''aide d''un animateur professionnel. Tout est réuni pour leur faire vivre une expérience unique, dans les conditions d’un concert. Pour éviter tout trou de mémoire, nous avons repris les codes du karaoké : des micros et des écrans pour faire défiler les paroles. Les points forts de l’animation : ⭐ U...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/karaoke-1089'),
('Karaoke Live', 'Animation Show', 'Transformez vos collaborateurs en véritables Rock Stars avec un Karaoké LIVE ! Un karaoké joué par des musiciens professionnels. L’idée est simple : faire chanter vos collaborateurs sur scène avec de véritables musiciens professionnels. Tout est réuni pour leur faire vivre une expérience unique, dans les conditions d’un concert. Pour éviter tout trou de mémoire, nous avons repris les codes du karaoké : des micros et des écrans pour faire défiler les paroles. Les points forts de l’animation : ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/karaoke-live-1088'),
('Blindtest', 'Animation Show', 'Un Blindtest avec notre super animateur ! Vous connaissez peut-être le Blindtest, mais en avez-vous déjà animé avec un Animateur Pro? Répondez avec une application dédiée et développée spécifiquement pour répondre au besoin de Blindtest. Les points forts de l’animation ⭐ Une activité déjantée pour passer un moment fédérateur avec vos équipes. ⭐ Une livraison clé en main : la sonorisation de votre lieu est comprise, géré par l''animateur et son assistant. Au-delà d’une animation musicale pleine...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/blindtest-1087'),
('Blindtest Live', 'Animation Show', 'Un Blindtest joué par des musiciens en live L’idée est simple : faire jouer des morceaux en live par des musiciens professionnels, pour que chaque participant essaie de retrouver le plus vite possible avec son équipe le nom de l’artiste et le titre de la chanson. Le BlindTest Live est joué par des musiciens chevronnés qui n’ont qu’un seul objectif : vous faire vivre un moment inoubliable. Les points forts de l’animation ⭐ Une activité déjantée pour passer un moment fédérateur avec vos équipes...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/blindtest-live-1085'),
('Karaoké Nomade', 'Animation Show', 'Découvrez une animation incontournable pour vos événements avec la borne karaoké nomade ! Que ce soit pour une soirée d''entreprise, un mariage, un anniversaire ou toute autre célébration, notre jukebox portable apportera une ambiance festive et conviviale où que vous soyez. La location comprend la borne de karaoké mobile équipée d''une enceinte amplifiée, une table de mixage, notre logiciel de karaoké avec plus de 66 000 titres régulièrement mis à jour, et 4 micros sans fil. Facile à utiliser,...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/karaoke-nomade-1081'),
('DJ COOKER MUSIC', 'Animation Show', 'Dj élevé dans la musique depuis l’enfance, de la disco à la French Touch, de la chanson française à la musique commerciale, Samuel est là pour vous faire danser !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/dj-cooker-music-1068'),
('DJ AMELKISS', 'Animation Show', 'DJ AMELKISS animera toutes vos soirées! Il peut personnaliser la musique en fonction de vos préférences et de l''ambiance de la soirée.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/dj-amelkiss-1051'),
('Mentaliste Magicien', 'Animation Show', 'Transportez vos invités dans une ballade mentale inédite, étonnante et troublante même pour les plus sceptiques d''entre eux. Le mentalisme est une spécialité de la magie qui apparaît désormais dans de nombreux événements : mariage, soirée privée, team building. Nhat réalise des numéros de transmission de pensée, d''influence et de prédiction. L’expérience inédite que vous propos. L''expérience inédite de mentalisme est à la fois spectaculaire et divertissante. Cette animation marquera les espri...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/mentaliste-magicien-1026'),
('Atelier - Théâtre & Vins', 'Animation Show', 'Initiez-vous à la dégustation sensorielle et prenez un shoot émotionnel avec une magnifique pièce de théâtre ! Au programme, vous trouverez une initiation à la dégustation sensorielle ; Anthocyane, la pièce de théâtre qui fait aimer le vin et selon vos envies un dîner accord mets et vins en 3 services et 5 vins.Initiez-vous à la dégustation sensorielle et prenez un shoot émotionnel avec une magnifique pièce de théâtre ! Il suffit de tendre le bras pour toucher les comédiens qui se produisent ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/atelier-theatre-vins-1023'),
('Le cirque', 'Animation Show', 'Des artistes professionnels lié à l''univers du cirque interviennent pour vos événements pour vous présenter leur show spectaculaire ! Faites rêver vos convives avec un troupe d''artiste locaux avec un panel de numéros dans la plus pure tradition du cirque de toujours.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/cirque-1017'),
('DJ Généraliste', 'Animation Show', 'Découvrez notre prestation DJ set pour tous vos événements ! Que vous soyez fan de musique généraliste, house, disco, funk ou techno, notre DJ saura créer l''ambiance parfaite pour satisfaire tous les goûts et toutes les ambiances. Pour une expérience sonore et visuelle optimale, optez pour notre système de sonorisation et de lumières en option. Choisissez les équipements qui répondent le mieux à vos besoins et faites de votre événement un moment inoubliable ! Pourquoi Choisir notre DJ Set pou...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/dj-generaliste-939'),
('Cours - Magic webinar', 'Animation Show', 'Le concept : Les participants découvriront un show, mêlant magie et expérience de mentalisme, dans lequel ils seront amenés à apprendre des secrets magiques simples à pratiquer avec des objets du quotidien. Les bénéfices : Ce cours de magie permettra de partager un moment entre équipe et devenir des apprentis magiciens. Le bon timing : Cette activité pourra être appliqué en fin de semaine pour partir en week-end sur un moment de partage et apprendre les tours appris à vos familles. Le déroule...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/cours-magic-webinar-885'),
('Instrument - Saxophone', 'Animation Show', 'SaxoMix est une prestation musicale dans laquelle un saxophoniste joue en live tout en mixant différents styles de musique sur ordinateur (lounge, neo soul, electro swing, house funky) ou plus simplement sur des classiques de jazz. Ce musicien peut aussi improviser sur une sélection de chansons qui vous tiennent à cœur. En option : ajouter un guitariste ou un percussionniste à cette formule afin d’enrichir la prestation.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/instrument-saxophone-853'),
('Tarologie', 'Animation Show', 'Très en vogue, le tarot est un outil remarquable pour rendre votre soirée mémorable. Une voyance bienveillante, saupoudrée d''humour et de légèreté sera offerte à vos invités qui se verront boostés par des conseils personnels et voudront les partager avec le reste des convives. Tarologue de profession, la voyante accompagne les invités dans leurs questionnements ; les cartes étant un merveilleux guide pratique pour améliorer son approche du quotidien. Rires et bonne humeur assurés ! Nous vous ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/tarologie-820'),
('Brazilian show', 'Animation Show', 'Profitez d''un moment haut en couleurs avec vos convives lors de votre événement ! Laissez place à la diversité culturelle d''un spectacle folklorique autour de danses brésiliennes. Découvrez de magnifiques tenues étincelantes au son des rythmes endiablés du Brésil dans un show singulier grâce à nos danseuses, musiciens, chanteurs et capoeiristes. Déroulé du show : - 3 passages avec changement de costumes à chaque fois. - 1er passage de 10mn, 2e passage de 15mn et 3e passage de 35mn.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/brazilian-show-815'),
('DJ', 'Animation Show', 'Bénéficiez de notre catalogue avec de nombreux artistes professionnels. Déterminons ensemble vos critères, nous sélectionnerons pour vous le meilleur DJ. Une offre éclectique et riche pour répondre à toutes les demandes en toutes occasions. Expérimentés, nos DJs maitrisent et s’adaptent aux différents styles musicaux. Solution tout-en-un, matériel de sonorisation et éclairage professionnel. Nos DJs font danser leurs invités : Parc des Princes, PSG, Stade Français, AccorHotels Arena, Vedettes ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/dj-807'),
('Paillettes & fluo party', 'Animation Show', 'Envie de colorer vos soirées ? Découvrez nos ateliers de maquillage artistique et moderne, où les invités peuvent se faire maquiller par des artistes bodypaint et paillettes. Profitez de nos deux offres : - un atelier maquillage à paillettes biodégradables - un atelier maquillage fluorescent artistique où vos invités sont maquillés avec de la peinture réactive à la lumière UV. Il est possible de coordonner les maquillages à un thème (couleur, motif...). Le petit plus : vous pouvez si vous le ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/paillettes-fluo-party-773'),
('Solo dance show', 'Animation Show', 'Danseur, chorégraphe et coach, Youri aime partager son art à travers des shows, collaborations, initiations ou encore des cours personnalisés. Il participe et gagne de nombreuses compétitions, danse dans la comédie musicale « Résiste », se produit dans différents événements en solo ou en groupe et collabore avec de nombreux artistes et enseignes comme The Black Eyed Peas ou Nike. Cette fois-ci c''est avec vous que Youri vous partage sa passion ; il s''adapte parfaitement à vos besoins dans un s...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/show/solo-dance-show-734'),
('Dégustation de café de spécialité', 'Animation Cocktail', 'Découverte Exquise du Café de Spécialité avec Pesette. Plongez dans l''univers raffiné du café de spécialité avec Pesette, où chaque grain raconte une histoire unique. Cet atelier sensoriel vous invite à explorer l''art et la science (chimie) derrière le café, de la cerise à la tasse. Goûtez à une sélection de 3 à 5 cafés différents, chacun avec ses propres nuances aromatiques. Apprenez à préparer le café comme un barista professionnel, en maîtrisant diverses méthodes, de la machine automatique...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/degustation-cafe-specialite-1187'),
('Le cocktail Likido', 'Animation Cocktail', 'Sublimez vos événements avec nos cocktails créations ! En nous confiant la dynamique de vos cocktails, vous bénéficiez des connaissances et de l''expertise de notre équipe. En effet, que ce soit pour une soirée d''entreprise, une fête de fin d''année ou un anniversaire, nos mixologues vous apportons une touche unique avec des ingrédients d''exception.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/cocktail-likido-1053'),
('Le bar de mixologie', 'Animation Cocktail', 'Réception clients ? Lancement de produit ? Fête de fin d''année ? Anniversaire ? Ou même soirée entre amis ? Votre événement est unique, votre bar à cocktails se doit de l''être aussi ! Pour cela un mixologue se déplace sur votre événement pour vous préparer sa sélection de cocktails. Détails : Cette offre comprend : - Bartender mixologue pendant 2 heures - 1 mixologue pour 50 personnes - 1h de montage et 1h de démontage - Ingrédients et spiritueux nécessaires à l''élaboration des cocktails - 2 ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/bar-mixologie-968'),
('Le bar à cocktails mobile - Open bar', 'Animation Cocktail', 'Une offre Open Bar Cocktail pour un événement réussi. Deux mixologues se déplacent sur tous vos événements et vous proposent de vous réunir autour de délicieux cocktails. Réception clients ? Lancement d''un produit ? Fête de fin d''année ? Anniversaire ? Nous vous proposons de recréer un bar à cocktails sur le lieu de votre événement selon vos envies. Cocktails : - Le Jardin anglais : gin, jus de concombre maison, sirop de concombre, citron vert. - La Grande Ourse : vodka, sirop de rose, chartr...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/bar-a-cocktails-mobile-open-bar-967'),
('Team Building Cocktail', 'Animation Cocktail', 'Renforcez les liens de vos équipes avec nos ateliers cocktails ! Nos barmans partageront leurs savoir-faire avec votre team. Cette activité ludique est orchestrée par un mixologue dynamique qui vous aidera à élaborer et à déguster de succulents cocktails. Le petit plus : nos mixologues exercent dans les meilleurs bars parisiens.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/team-building-cocktail-633'),
('Les cocktails en bouteille', 'Animation Cocktail', 'Faites vous livrer vos meilleurs cocktails sous forme de bouteilles pour vos événements ! Au choix : – Jardin Anglais : Gin / Jus de concombre maison / Sirop de concombre / Jus de citron vert – Des Chiffres et des Loutres : Gin infusé au thym / Dolin rouge / Sirop de figues / Jus de citron – Baloo : Rhum ambré / Sirop d’épices / Jus de citron vert / Tabasco – Grande Ourse : Vodka infusée aux baies roses / Chartreuse jaune / Sirop de rose / Jus de citron / Ginger beer – Old Fockin’ Fashioned :...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-cocktail/cocktails-bouteille-632'),
('Découverte des gins français', 'Animation Cuisine', 'Découvrez les dessus du monde du Gin et devenez maitre dans l''art du Gin Tonic! Déroulé: - Présentation du gin français et de ses régions - Dégustation de 6 gins français aux profils différents - Réalisation du parfait Gin & Tonic cocktail Objectifs: - Découvrir les gins français et leurs diversités - Stimuler la convivialité et l''échange - Apprendre à réaliser un cocktail', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/decouverte-gins-francais-1084'),
('Découverte des spiritueux d''Ile de France', 'Animation Cuisine', 'Partez à la découverte de 5 distilleries d''ile de France! Déroulé : - Dégustation de 5 spiritueux produits en Île-de-France - Apprentissage des techniques de dégustation et découverte des histoires et des caractéristiques de chaque spiritueux - Échanges et discussions autour des spiritueux dégustés Objectifs : - Explorer la richesse et la diversité des spiritueux franciliens - Développer le sens du goût et l''odorat - Stimuler la fierté locale et l''esprit de découverte - Partager un moment de ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/decouverte-spiritueux-ile-france-1083'),
('Dégustation à l''aveugle de spiritueux français', 'Animation Cuisine', 'Venez challenger votre palais avec nous ! Réussirez-vous à retrouver les spiritueux qui se cachent dans vos verres ? Déroulé : Dégustation de 6 spiritueux différents Bouteilles non dévoilées Découverte des origines et des caractéristiques de chaque spiritueux Objectifs : Développer le sens du goût et de l''odorat Apprendre à identifier les différents arômes présents dans les spiritueux !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/degustation-a-aveugle-spiritueux-francais-1082'),
('Gâteaux ou pâtisseries personnalisés', 'Animation Cuisine', 'Proposez des pièces sur-mesures lors de vos évènements. N''hésitez pas à nous contacter pour vos événements à thème, nous nous ferons un plaisir d''adapter nos pâtisseries pour y répondre. La tarification des pâtisseries personnalisées dépend du nombre de personnes et des détails de personnalisation souhaités. Ensemble, nous établirons une offre qui répond à vos attentes.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/gateaux-ou-patisseries-personnalises-1050'),
('Atelier de biérologie', 'Animation Cuisine', 'Découvrez l’univers de la bière artisanale lors d’ateliers de dégustation conviviaux et pédagogiques. Pendant 1h30, notre biérologue vous apprend à déguster en utilisant vos cinq sens. A travers la dégustation de 4 bières différentes, Vous découvrirez les styles, les ingrédients et les procédés de fabrication. Le tout dans une ambiance conviviale et d’échanges !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/atelier-bierologie-1049'),
('Atelier de cuisine personnalisé', 'Animation Cuisine', 'Challenge culinaire, élaboration d''un menu entrée / plat / dessert ou atelier sucré, les recettes sont à définir ensemble en fonction de vos préférences et intolérances alimentaires. Il est également possible de proposer un atelier suivi d’un repas. Exemples de menus : - Tartare aux 3 saumons - Filet de cabillaud au champagne et purée façon Robuchon - Atelier : Tiramisu Ispahan (rose, pistache et fruits rouges)', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/atelier-cuisine-personnalise-1011'),
('Atelier - Les secrets du vin', 'Animation Cuisine', 'Découvrez les secrets du vin avec cet atelier d''assemblage d''une durée d''1h30. Chaque participant pourra ainsi créer une cuvée unique en assemblant deux cépages de vins rouges. À la fin de l''atelier, chacun pourra partir avec sa bouteille personnalisée. Le prix peut varier en fonction du nombre de participants. N''hésitez pas à contacter nos chefs de projet pour un devis personnalisé.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/atelier-secrets-vin-983'),
('La dégustation accord mets-vins', 'Animation Cuisine', 'Profitez de cet atelier pour rassembler vos convives autour d''une activité ludique et gourmande au Domaine Bouche-du-Roi ou au siège de votre entreprise. Pour une durée d''1h30, un animateur vous présentera l''histoire du Domaine. Vous dégusterez également quatre cuvées unique, chacune accompagnée de quatre bouchées signature. Ces mets sont issus de produits locaux achetés en circuit court. Un véritable voyage sensoriel ! Les prix affichés varient en fonction du nombre de personne. N''hésitez pa...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/degustation-accord-mets-vins-982'),
('La dégustation de vin', 'Animation Cuisine', 'Conviez vos collaborateurs pour une dégustation d''exception au domaine du Bouche-du-Roi ou au siège de votre entreprise. Cette animation d''une heure vous permettra d''en apprendre plus sur le Domaine et déguster quatre cuvées à l''aveugle. Ainsi, vous pourrez élargir vos connaissances sur le vin en goutant les vins suivants : - Chardonnay blanc – Chenin blanc – Merlot rouge – 4 cépages Rouge. Le prix varient en fonction de nombre de personnes. N''hésitez pas à contacter nos chefs de projet pour ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/degustation-vin-981'),
('Cours - Cuisine avec Top Chef', 'Animation Cuisine', 'Le concept : Envie de vous mettre dans la peau d''un vrai chef cuisinier ? Enfilez vos plus beaux tabliers et laissez vous guider par ce célèbre chef de l''émission culinaire que nous connaissons tous ; Merouan de la saison 10 de Top Chef. Les bénéfices : Ce cours permet à vos équipes de se détendre en passant un moment fun et rassemblant avec ce chef talentueux à la répartie sans faille qui vous donnera le sourire ! Le bon timing : Ce cours d''une heure est une occasion parfaite pour organiser ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/cours-cuisine-avec-top-chef-920'),
('Atelier - À la découverte de l''huile d''olive', 'Animation Cuisine', 'Le concept : Savez-vous qu''il existe 2000 variétés d''olives ? Faites vous transporter par les savoirs de cet atelier d''oléologie ; l''occasion de découvrir les secrets de l''huile d''olive, ce produit que nous utilisons tous mais que nous méconnaissons ! Faites vous guider par une véritable experte sur le sujet en dégustant différents types d''huiles tout en acquérant des connaissances sur sa fabrication. Les bénéfices : Cet atelier ludique et convivial est l''occasion de faire voyager vos collabo...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/atelier-a-decouverte-huile-olive-919'),
('Cours - Sablés aux fleurs', 'Animation Cuisine', 'Le concept : Offrez-vous un cours qui mêle gourmandise et naturopathie ! Notre cheffe nous apprend à intégrer du végétal dans notre quotidien avec cette recette gourmande de sablés aux fleurs. Les bénéfices : Cette activité cuisine permettra de souder les équipes dans une atmosphère conviviale et gourmande. La formation naturopathe de notre cheffe donne de la profondeur à ce cours de cuisine atypique. Le bon timing : Ce cours peut faire partie intégrante d’un séminaire ou faire l’objet d’un c...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/cours-sables-aux-fleurs-892'),
('Cours - Réaliser une recette vegan', 'Animation Cuisine', 'Le concept : Offrez-vous un cours qui mêle gourmandise et naturopathie ! Notre cheffe nous apprend à intégrer du végétal dans notre quotidien avec une recette définie en amont. Les bénéfices : Cette activité cuisine permettra de souder les équipes dans une atmosphère conviviale et gourmande. La formation naturopathe de notre cheffe donne de la profondeur à ce cours de cuisine atypique. Le bon timing : Ce cours peut faire partie intégrante d’un séminaire ou faire l’objet d’un cadeau de remerci...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/cours-realiser-une-recette-vegan-891'),
('Dégustation - Fromages de France', 'Animation Cuisine', 'Le concept : Retrouvez tous vos collègues pour une dégustation de fromages interactive en ligne et en direct co-animée par un Meilleur Ouvrier de France. Les bénéfices : Cette dégustation sera idéale pour cohésion d’équipes (et/ou clients & partenaires) en proposant une activité ludique, éducative, gourmande et chaleureuse. Le bon timing : Cette activité sera parfaite comme activité d’afterwork, pour finir la semaine sur une touche gourmande et créatrice de liens sociaux. Le déroulement : - u...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/degustation-fromages-france-886'),
('Fût Bière Artisanale Felsgold', 'Animation Cuisine', 'Découvrez notre fût de 30L de la brasserie Felsgold ! La marque Felsgold vous permet de déguster des bières d’excellente qualités. La bière est produite au sein de la brasserie de Saint-Omer dans le Pas-de-Calais. Cette brasserie indépendante a su concilier des techniques artisanales et des procédés de fabrication à la pointe de la technologie pour vous offrir de savoureuses bières françaises. Le plus : moelleuse et rafraîchissante, sa mousse blanche et son houblonnage équilibré lui confèrent...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/fut-biere-artisanale-felsgold-805'),
('Les Sablés à Colorier', 'Animation Cuisine', 'Une animation qui allie fun et gourmandise, un sablé qui représente votre évènement pour communiquer sur votre univers, vos produits ou célébrer une période phare de l’année ( Noel ,Pâques , ... ), les sablés à colorier font appel à la créativité et crée du lien à travers une animation originale La recette : Sablé vanille et fleur de sel recouvert de glace royale Nous pouvons mettre à votre disposition une animatrice pour dynamiser un stand lors d''un événement - sur devis.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/sables-a-colorier-797'),
('Les sablés gravés', 'Animation Cuisine', 'Les sablés gravés savent faire passer en douceur le message que vous souhaitez. Je t''aime, Bravo, Coucou, Merci, slogan ou état d''esprit de votre évènement ... Découvrez les sablés à messages pur beurre à la Carte et créez votre biscuit personnalisé ! Les sablés sont à la vanille & fleur de sel et décorés à la main avec des couleurs naturelles, de la créativité & beaucoup d''amour. Les sablés gravés sont une excellente façon de communiquer avec douceur le message que vous souhaitez transmettre...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/sables-graves-796'),
('Les pièces montées de bonbons', 'Animation Cuisine', 'Célébrez le partage et la joie avec nos pièces montées de bonbons, parfaites pour des moments gourmands et conviviaux ! Notre création phare : une pyramide colorée de délices, couronnée d''une sucette géante "SUGAR FREE". Idéale pour tous événements, elle allie plaisir gustatif et présentation visuelle saisissante.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/pieces-montees-bonbons-795'),
('Les cupcakes brandés', 'Animation Cuisine', 'Pour identifier parfaitement et immédiatement votre marque via un logo ou un élément graphique, ce gâteau individuel est le format idéal pour une dégustation facile ou à offrir . Découvrez plus de 16 parfums avec moelleux vanille, fraise, framboise, speculoos ou chocolat !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/cupcakes-brandes-794'),
('Bubble Waffle', 'Animation Cuisine', 'Savourez ces nouvelles découvertes venant d''Hong Kong où elles sont depuis les années 50 une gourmandise incontournable qu’il est possible de déguster à chaque coin de rue. La pâte de ces gaufres à bulles est préparée par notre Chef, elle sera cuite devant vos convives et servie avec des toppings de votre choix. Les gaufres sont dorées et croustillantes à l’extérieur, et moelleuses à l’intérieur. 6 toppings au choix: - coulis de fruit rouge - fruits frais - chantilly - nutella - oreo - caramel', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-culinaire/bubble-waffle-781'),
('Atelier peinture sur céramique', 'Animation Durable', 'Les ateliers Pahome offrent bien plus qu’un simple moment créatif : ils sont pensés pour stimuler l’esprit d’équipe, et favoriser l’expression individuelle. Les ateliers proposés sont ludiques, collaboratifs et accessibles à tous. Ils permettent à chacun de découvrir la peinture sur céramique. Ces moments partagés invitent à ralentir, à se recentrer et à vivre une expérience authentique qui laissera une empreinte durable dans les esprits. Détails : Les tarifs proposés incluent : – les céramiq...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/atelier-peinture-ceramique-1189'),
('Ateliers de sensibilisation aux enjeux écologiques', 'Animation Durable', 'Êtes-vous prêt à insuffler un véritable élan de changement au sein de votre entreprise et à placer les enjeux écologiques au cœur de vos préoccupations ? Les ateliers de sensibilisation offrent bien plus qu''une simple prise de conscience. Ils sont conçus pour catalyser l''action, encourager l''engagement et guider votre organisation vers des pratiques plus durables. Les ateliers ludiques et collaboratifs qui sont proposés vont bien au-delà des approches traditionnelles de sensibilisation. Parmi...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/ateliers-sensibilisation-aux-enjeux-ecologiques-1080'),
('Atelier - Bouquet de fleurs comestibles', 'Animation Durable', 'Apprenez à composer des bouquets de fleurs et feuillages comestibles, vous découvrirez également les vertus de ces plantes ainsi que leurs utilisations en cuisine. Tulipe sur le gâteau : une petite dégustation florale est prévue en fin d’atelier.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/atelier-bouquet-fleurs-comestibles-851'),
('Décoration florale - Table', 'Animation Durable', 'Ajoutez une touche de green, de fraîcheur et de bien-être à votre événement grâce à des bouquets frais et sauvages, composés à la main par une équipe d’artisans-fleuristes hyper créative. Spécialement imaginés pour vous, découvrez 3 packs au choix pour vous accompagner dans la réalisation et la réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M - Pack M : assortiment de 10 fioles + 2 bouquets S + 2 bouquets M - Pack L : assortiment de 15 fioles + 3 ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-table-827'),
('Décoration florale - Rooftop', 'Animation Durable', 'Habillez sans plus attendre le rooftop, terrasse ou jardin de votre lieu et même ses intérieurs pour apporter une dose de bonne humeur et de chaleur grâce à des bouquets frais, sauvages et colorés, composés à la main par une équipe d’artisans-fleuristes hyper créative. Spécialement imaginés pour vos cocktails, découvrez 3 packs au choix pour vous accompagner dans la réalisation et la réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M - Pack M : asso...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-rooftop-826'),
('Décoration florale - Champêtre', 'Animation Durable', 'Osez la décoration champêtre sur votre lieu d''événement pour rappeler l’ambiance de la forêt et de la nature grâce à des bouquets frais, sauvages et colorés, composés à la main par une équipe d’artisans-fleuristes hyper créative. Chacun s’y retrouvera et appréciera l’univers cosy et chaleureux. Spécialement imaginés pour vous, découvrez 3 packs au choix pour vous accompagner dans la réalisation et réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M +...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-champetre-825'),
('Décoration florale - Tropical vibes', 'Animation Durable', 'Que ce soit pour un cocktail d''entreprise, un événement presse, un anniversaire ou un apéro entre amis, vous aussi succombez à la décoration Tropical vibes ! Décorez sans plus attendre votre lieu avec des bouquets frais, sauvages et colorés, composés à la main par une équipe d’artisans-fleuristes hyper créative. Passez un moment d''évasion, soleil, îles vierges et exotisme avec vos convives grâce à une décoration colorée et ultra branchée. Spécialement imaginés pour vous, découvrez 3 packs au ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-tropical-vibes-824'),
('Décoration florale - All white', 'Animation Durable', 'Apportez une touche élégante à votre réception grâce à des bouquets frais et sauvages all white composés à la main par une équipe d’artisans-fleuristes hyper créative. Spécialement imaginés pour vous, découvrez 3 packs au choix pour vous accompagner dans la réalisation et réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M - Pack M : assortiment de 10 fioles + 2 bouquets S + 2 bouquets M - Pack L : assortiment de 15 fioles + 3 bouquets M + 3 bouquets L', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-all-white-823'),
('Décoration florale - Banquet', 'Animation Durable', 'Que ce soit pour un petit-déjeuner presse, un déjeuner ou un dîner confidentiel, apportez-y une touche personnalisée grâce à des bouquets frais, sauvages et colorés composés à la main par une équipe d’artisans-fleuristes hyper créative. Spécialement imaginés pour votre événement, découvrez 3 packs au choix pour vous accompagner dans la réalisation et la réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M - Pack M : assortiment de 10 fioles + 2 bouque...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-banquet-822'),
('Décoration florale - Cocktail', 'Animation Durable', 'Vous souhaitez apporter une touche personnalisée à votre événement ? Décorez sans plus attendre votre lieu avec des bouquets frais, sauvages et colorés, composés à la main par une équipe d’artisans-fleuristes hyper créative. Spécialement imaginés pour vos cocktails, découvrez 3 packs au choix pour vous accompagner dans la réalisation et la réussite de tous vos projets : - Pack S : assortiment de 10 fioles + 1 bouquet S + 1 bouquet M - Pack M : assortiment de 10 fioles + 2 bouquets S + 2 bouqu...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/decoration-florale-cocktail-821'),
('Conférence green', 'Animation Durable', 'Envie de promouvoir le développement durable dans l''entreprise ? Besoin d’éduquer vos collaborateurs sur de nouvelles valeurs éco-responsables ? Dans tous les cas, voyons comment y remédier avec des conférences originales et riches en informations. Chacune de nos conférences cible, afin de l’approfondir au maximum, une thématique précise. Voici deux propositions : 1001 idées reçues, mieux comprendre les arbres. Les fabuleux progrès scientifiques des dernières années nous aident à mieux compre...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/conference-green-818'),
('Le Poker vert', 'Animation Durable', 'Découvrez une animation développement durable inspirée des règles du Poker, où stratégie et bluff sont de mise ! Le Poker vert est une animation à la mécanique de jeu spécialement étudiée pour rendre le développement durable désirable ! Le jeu se joue autour d’authentiques tables de casino réadaptées, avec des cartes sur lesquelles sont inscrites des questions portant sur l’univers RSE. À tour de rôle, les joueurs s’affrontent à coup de bluff et de relances, afin d’amasser un maximum de jeton...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/poker-vert-747'),
('Les pailles écologiques personnalisables', 'Animation Durable', 'Découvrez notre sélection de pailles écologiques et sans plastique pour répondre aux besoins d''événements responsables. Elles peuvent êtres flexibles, droites, courbées, colorées ! Paille en bambou personnalisée : Cette paille en bambou est naturelle, réutilisable et ne pollue pas l’environnement. Elle est un accessoire original pour la consommation de toutes les boissons chaudes et froides et se nettoie facilement à l’aide d’une brosse vendue avec. Paille en inox personnalisée : La paille en...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/pailles-ecologiques-personnalisables-692'),
('Les pailles écologiques', 'Animation Durable', 'Découvrez notre sélection de pailles écologiques et sans plastique pour répondre aux besoins d''événements responsables. Elles peuvent êtres flexibles, droites, courbées, comestibles et colorées ! Paille en pomme : C''est une paille comestible produite à base de fibres naturelles. Biodégradable et compostable, elle est sans sucre ajoutée, sans lactose et convient aux boissons chaudes ou froides. Elle convient parfaitement aux vegans. Paille en pâte : La paille en pâte est jetable, biodégradable...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/pailles-ecologiques-691'),
('Animation cocktail tableau floral', 'Animation Durable', 'Des toiles, des chevalets ? Le principe de cette activité est simple : vous choisissez le message que vous souhaitez faire passer, puis vous l’écrivez sur les toiles… avec des fleurs. Sur ce stand, chaque participant prend quelques minutes pour cueillir, planter et écrire avec des fleurs. Au bout de l’événement et sous les bons conseils de l’animateur, votre message a pris forme. Terriblement efficace, que ce soit pour une réception, un séminaire thématique, un arbre de Noël, ou toute autre b...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/animation-cocktail-tableau-floral-688'),
('Le bar à plantes', 'Animation Durable', 'Pour égayer votre événement de manière originale, cette animation installe ses stands Do It Yourself sur votre lieu de réception. En entrant dans la pièce, les invités sont attirés par un bel étalage de plantes : tout ce vert, ça fait déjà du bien ! De la terre, des graviers, un joli récipient en verre : il ne reste plus qu’à choisir sa mini-plante pour fabriquer en quelques minutes un jardin de poche à rapporter à la maison ou au bureau. Une animation originale et gratifiante pour réveiller ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/bar-a-plantes-687'),
('Atelier Terrarium', 'Animation Durable', 'Sous leurs airs sauvages et vintages, ces jardins miniatures présentent de nombreux avantages. Protégés de tout, ils se contentent du minimum et nous apprennent beaucoup sur la vie des plantes. Une bonne occasion de différencier les écosystèmes secs et humides, et de partager quelques connaissances botaniques. Les terrariums peuvent ensuite s’exposer au bureau ou s’emporter à la maison. Chacun est invité à renouer avec la nature… et à la bichonner. Une activité écolo-conviviale qui laissera a...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/atelier-terrarium-686'),
('Atelier Kokedama', 'Animation Durable', 'Une sphère de terre recouverte de mousse, de la ficelle, quelques plantes vertes et sauvages, c’est tout ce qu’il faut pour cet atelier. Tels des jardins suspendus ou posés sur leur socle, les kokedamas composés de 3 plantes, impressionnent par leur simplicité, leur style et leur ingéniosité. Si cet anti-stress a su traverser les âges et les frontières, il doit y avoir une bonne raison ! Le secret de cet art japonais ? Il nécessite la coopération de plusieurs participants pour prendre vie. Et...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/atelier-kokedama-685'),
('Jeux en bois géants', 'Animation Durable', 'Les jeux en bois géants traditionnels permettent de créer une animation adaptée à tous types d’événements, qu’ils soient professionnels ou personnels. Les possibilités sont multiples pour créer la surprise ! Ils garantiront une excellente ambiance et raviront tous les participants, la simplicité de leurs règles les met à la portée de tous ! Cette animation est couplée avec un maître de jeux qui dynamisera cette dernière et incitera vos convives à découvrir la sélection de jeux. Le petit plus ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-durable/jeux-bois-geants-671'),
('L''atelier "do-in"', 'Animation Bien-Être', 'Initiez-vous aux techniques d''automassage issues de la médecine traditionnelle japonaise. Nos professionnels axeront la séance en fonction des problématiques soulevées par vos salariés : maux de tête, fatigue, douleurs dorsales, cervicales, jetlag, jambes lourdes etc.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-do-in-1001'),
('L''atelier sophrologie', 'Animation Bien-Être', 'Profitez des savoirs d''un expert en sophrologie pour développer vos connaissances sur cette pratique psycho-corporelle. Vous pourrez ainsi apprendre des techniques pour apaiser son esprit et mieux gérer les émotions négatives. Cet atelier est disponible en physique ou en distantiel.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-sophrologie-1000'),
('Cours - Les bases de l''aromathérapie', 'Animation Bien-Être', 'Le concept : Dans ce cours, vous apprendrez à prendre soin de vous de manière naturelle. Julia, notre intervenante, vous présentera 10 huiles essentielles de bases qui constituent votre pharmacie naturelle. Les bénéfices : Cette apprentissage ludique permettra de passer un moment entre équipe qui resserra les liens tout en apprenant des techniques pour se faire du bien. Le bon timing : Cet atelier sera parfait un vendredi pour pouvoir laisser de côté les problèmes rencontrés durant la semaine...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/cours-bases-aromatherapie-890'),
('Cours - Yoga nidra', 'Animation Bien-Être', 'Le concept : Le yoga nidra est une profonde relaxation guidée qui se pratique en étant allongé. Laissez vous porter par la voix de Julia, notre professeure, pour un lâcher-prise en profondeur et vous sentir comme sur un nuage. Les bénéfices : Ce cours de yoga permettra à vos équipes d’avoir un meilleur sommeil, d’être moins stressé, de lâcher prise avec moins de pensée négatives tout en gérant mieux ses émotions. Le bon timing : Cette activité est idéale en début ou fin de journée pour insuff...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/cours-yoga-nidra-889'),
('Cours - Initiation à la méditation', 'Animation Bien-Être', 'Le concept : Tournez le bouton sur le mode « pause » et venez prendre plusieurs profondes respirations. Cette animation propose des méditations simples et accessibles aux débutants, pour ralentir son rythme, retrouver plus de calme et surtout prendre un moment pour soi. Les bénéfices : Ce cours permettra à vos équipes de mieux gérer leurs stress et potentielle anxiété tout en favorisant l’attention et la mémoire. Le bon timing : Cette activité sera parfaite après des réunions hebdomadaires qu...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/cours-initiation-a-meditation-888'),
('Cours - Yoga', 'Animation Bien-Être', 'Le concept : Passez un moment de bien-être entre équipe avec ce cours de yoga qui permettra à vos collaborateurs de découvrir ou pratiquer cette discipline de détente à travers des exercices de respiration, méditation et relaxation. Les bénéfices : Cette activité permettra à vos collaborateurs de mieux gérer leurs stress tout en apportant un shot de bonheur et de lâcher prise, soit le plein d’outils pour garantir la bonne ambiance et la productivité. Le bon timing : Ce cours de yoga sera idéa...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/cours-yoga-887'),
('Massage bien-être express', 'Animation Bien-Être', 'N''est-ce pas un rêve de se faire masser pendant un événement ? C''est désormais possible grâce au massage Amma Assis effectué sur une chaise ergonomique pour une vraie bulle de détente. Ce massage a spécialement été développé pour être réalisé en position assise, et détendre les zones les plus tendues : trapèzes, nuque, épaules et bras. Les massages durent entre 10 et 20 minutes, la pause parfaite au quotidien ! Le seul besoin ? 3m2 de surface pour la chaise ergonomique. Découvrez deux types d...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/massage-bien-etre-express-799'),
('Atelier - Création tisane et thé aux fleurs', 'Animation Bien-Être', 'Offrez un moment de détente et créatif à vos convives grâce à cet atelier création de tisane aux fleurs. Découvrez comment associer les saveurs et les bienfaits des fleurs pour créer votre tisane ou thé sur-mesure !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-creation-tisane-the-aux-fleurs-715'),
('Atelier - Initiation aux huiles essentielles', 'Animation Bien-Être', 'Alternative à la médecine traditionnelle, les huiles essentielles ont des propriétés aromathérapies, mais encore faut-il les connaitre ! Découvrez notre atelier pour découvrir les bienfaits des huiles essentielles et apprendre à les utiliser.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-initiation-aux-huiles-essentielles-714'),
('Bar à tattoos', 'Animation Bien-Être', 'Proposez à vos convives une animation originale et ludique. Voici le bar à tatouages éphémères ! Les tatouages sont présentés de manière très esthétique à l''aide d''une structure en forme de grande roue. Il vous est également possible de personnaliser vos tatouages avec un logo ou le nom de votre entreprise (en amont avec un délai de 15 à 20 jours) en complément. Une option tatouage type QR Code ! En scannant le tatouage via une application celui-ci renvoie directement à une page web dédiée ou...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/bar-a-tattoos-569'),
('Concert en Odorama, Musique et Parfum', 'Animation Bien-Être', 'Nous vous proposons de vivre une expérience sensorielle unique et originale : profitez d’un concert tout en découvrant de grands parfums et des matières premières qui les composent, le tout raconté par une experte en parfumerie et une violoniste. Un moment artistique, entre culture et plaisir des sens. L''atelier se déroule en parallèle d''un concert de musique classique, baroque ou actuelle avec trois musicien, et découverte de parfums. Minimum : 40 personnes', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/concert-odorama-musique-parfum-347'),
('Atelier Champagnes & Parfums', 'Animation Bien-Être', 'Un atelier qui oscille entre culture, luxe, et expression des sens. Plusieurs parfums seront présentés, dont certains s''inspirent du spiritueux à bulles. Vous découvrirez aussi des arômes, ou "matières premières" utilisés dans les parfums, que l''on peut identifier également dans les champagnes. Ainsi vous "éduquez et entraînez votre sens de l''olfaction". Suivra une dégustation de 3 ou 4 champagnes issus des grands terroirs champenois, qui donne l''opportunité de comprendre les mystères du vin ...', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-champagnes-parfums-346'),
('Atelier parfums', 'Animation Bien-Être', 'Eveillez votre odorat ! Nous vous proposons un atelier parfum afin de comprendre leur composition, leur histoire, etc. Vous avez le choix entre ces différents formats : - Histoire de la parfumerie et atelier d''olfaction (parfums et matières premières) - Histoire de la parfumerie et création de parfum - atelier d''olfaction (parfums et matières premières) et - Création de Parfum Minimum : 10 personnes Maximum : 80 personnes', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/atelier-parfums-344'),
('Makeup Bar', 'Animation Bien-Être', 'Un atelier pour sublimer vos jolis minois ! Sublimez vos atouts naturels entre les mains expertes de nos maquilleuses : avec un focus yeux, teint ou lèvres, à vous ce petit truc en plus irrésistible !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/makeup-bar-276'),
('Hair Bar', 'Animation Bien-Être', 'Quinze minutes pour donner un coup d’éclat à vos chevelures de rêve, c’est le challenge que nous relevons ! Nos coiffeurs réalisent, sur cheveux secs, des coiffures simples et efficaces, des tresses canons et intemporels… c’est à vous de voir !', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/hair-bar-275'),
('Nail Bar', 'Animation Bien-Être', 'Une mani’ de folie en un temps record ! Nos Nail Artistes s’occupent de vos invités : limage, polissage et pose de vernis ! Un temps et un résultat records : c’est LA manucure adulée des working girls.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/nail-bar-274'),
('Barber Shop', 'Animation Bien-Être', 'Nous vous proposons une animation mariant le meilleur de la tradition et une touche de modernité. Le Barber Shop charmera vos convives masculins par son ambiance relaxée et sa portée tendance. Notre équipe de barbier sera la pour sculpter et prendre soin de la barbe et/ou moustache de monsieur, et vous conseillera sur son entretient.', NULL, NULL, NULL, NULL, 'https://www.snapevent.fr/animation-evenementielle/paris/animation-bien-etre/barber-shop-261');

-- Vérification après insertion
SELECT COUNT(*) as animations_apres_ajout FROM animations;

-- Statistiques par type d'animation SnapEvent
SELECT 
    type_animation, 
    COUNT(*) as count 
FROM animations 
WHERE type_animation LIKE '%Animation%' OR type_animation LIKE '%Photo%' OR type_animation LIKE '%Vidéo%'
GROUP BY type_animation 
ORDER BY count DESC;

-- Toutes les catégories d'animations
SELECT DISTINCT type_animation 
FROM animations 
ORDER BY type_animation;

-- Exemples d'animations par catégorie
SELECT type_animation, nom, LEFT(description, 80) as description_courte
FROM animations 
WHERE description IS NOT NULL AND description != 'NULL'
ORDER BY type_animation, nom 
LIMIT 20;
